name: Build Android
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04 # Stable version for Buildozer
    steps:
      - uses: actions/checkout@v4

      - name: Install Buildozer Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip3 install --user --upgrade buildozer

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          buildozer android debug
        env:
          # This helps avoid some permission issues in CI
          BUILDOZER_ALLOW_KIVY_USER: 0 

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ChD-Android-Package
          path: bin/*.apk
